config/routes.rb
Rails.application.routes.draw do
  resources :matches
  devise_for :users
  resources :users

  root 'matches#index'
  get 'games/about'
  get 'games/myMatches'
  get 'games/ranking'

  match 'users/:id' => 'users#show', via: :get


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :matches

  has_attached_file :avatar,
    storage: :s3,
    s3_credentials: {
        access_key_id: ENV.fetch("AWS_ACCESS_KEY_ID"),
        secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
        s3_region: ENV.fetch('AWS_REGION'),
        bucket: ENV.fetch('S3_BUCKET_NAME')
    },
    path: ":attachment/:id/:style/:filename",
    url: "https://s3.us-east-2.amazonaws.com",
    styles: {
        medium: ["250x250#"],
        thumb: ["200x200#"]
    },
    :default_url => "/images/:style/missing.png"


  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:name, :email, :password, :vorname, :nachname, :avatar)}
      devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:name, :email, :password, :vorname, :nachname, :avatar, :current_password)}
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @allUsers = User.all
  end

  def about
  end

  def ranking
    @allUsers = User.all.order('score DESC')
  end

  def myMatches
    @matches = Match.all.order('created_at DESC')
    @matches_days = @matches.group_by {|match| match.created_at.to_date }

  end


end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all.order('created_at DESC')
    @matches_days = @matches.group_by {|match| match.created_at.to_date }
  end


  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = current_user.matches.build
    @user = current_user
    @allUsers = User.all.where("id != ?",current_user.id)
  end

  # GET /matches/1/edit
  def edit
    @user = current_user
    @allUsers = User.all.where("id != ?",current_user.id)
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = current_user.matches.build(match_params)
    @user = current_user
    @allUsers = User.all
    @player1 = User.find(params[:match][:player1])
    @player2 = User.find(params[:match][:player2])


    respond_to do |format|
      if @match.save

        if @match.scoreplayer1 < @match.scoreplayer2
          #player1 gewinnt das Spiel und bekommt die Differenz des matches auf seinen score gutgeschrieben
          @difference = @match.scoreplayer2 - @match.scoreplayer1

          @player1.update_column(:won_matches, @player1.won_matches + 1)
          @player1.update_column(:score, @player1.score + @difference)

          @player2.update_column(:lost_matches, @player2.lost_matches + 1)
          @player2.update_column(:score, @player2.score - @difference)
        else
          #player2 gewinnt das Spiel und bekommt die Differenz des matches auf seinen score gutgeschrieben
          @difference = @match.scoreplayer2 - @match.scoreplayer1

          @player2.update_column(:won_matches, @player2.won_matches + 1)
          @player2.update_column(:score, @player2.score - @difference)

          @player1.update_column(:lost_matches, @player1.lost_matches + 1)
          @player1.update_column(:score, @player1.score - @difference)

        end

        format.html { redirect_to @match, notice: 'Spiel erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Spiel erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:game, :player1, :player2, :scoreplayer1, :scoreplayer2)
    end

    def correct_user
      @match = current_user.matches.find_by(id: params[:id])
      redirect_to matches_path, notice: "Du darfst den Eintrag nicht verändern." if @match.nil?
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  @user = User.find(params[:id])
  @my_matches = Match.all
  #@my_matches_days = @matches.group_by {|match| match.created_at.to_date }
  #@player1 = current_user
  #@player1_matches = Match.all.select {|match| match.player1 = @user.id}
  #@player2_matches = Match.all.select {|match| match.player2 = @user.id}
  #@users_matches = @player1_matches + @player2_matches

  opponent = []
  @my_matches.each do |match|

      player1 = User.find(match.player1)
      player2 = User.find(match.player2)

      if (@user != player1) && (@user == player2)
        opponent.push(player1.id)
      end

      if (@user != player2) && (@user == player1)
        opponent.push(player2.id)
      end
  end

  opponent_matches = opponent.inject(Hash.new(0)) { |total, e| total[e] += 1 ;total}
  opponent_matches = opponent_matches.sort_by { |id, matches| matches }.reverse

  @player1_matches = Match.where({ player1: "4", player2: @user.id })



end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def date_format(date)
    date.strftime("Am %d.%m.%Y um %H:%M Uhr")
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper

  def win_or_lose(match)
    player1 = User.find(match.player1)
    player2 = User.find(match.player2)

    if player1 == current_user
        if match.scoreplayer1 < match.scoreplayer2
          wonmatch = 'Win'
        elsif match.scoreplayer1 > match.scoreplayer2
          wonmatch = 'Lose'
        else
          wonmatch = 'Draw'
        end
    elsif player2 == current_user
        if match.scoreplayer2 > match.scoreplayer1
          wonmatch = 'Win'
        elsif match.scoreplayer2 < match.scoreplayer1
          wonmatch = 'Lose'
        else
          wonmatch = 'Draw'
        end
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= fa_icon "gamepad 2x" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">

      <ul class="navbar-nav mr-auto">
        <%= link_to 'Alle Spiele', matches_path, class: "nav-item nav-link" %>
        <% if user_signed_in? %>
          <%= link_to 'Meine Spiele', games_myMatches_path, class: "nav-item nav-link" %>
          <%= link_to 'Neues Spiel', new_match_path, class: "nav-item nav-link" %>
        <% end %>
        <%= link_to 'Ranking', games_ranking_path, class: "nav-item nav-link" %>
      </ul>
    </div>

    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <ul class="navbar-nav">

        <% if user_signed_in? == false %>

            <%= link_to 'Login', new_user_session_path, class: "nav-item nav-link" %>
            <%= link_to 'Registrieren', new_user_registration_path, class: "nav-item nav-link" %>


        <% else %>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag(current_user.avatar.url(:thumb), class:'nav_avatar')%>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <%= link_to 'Editieren', edit_user_registration_path, class: 'dropdown-item'%>
                  <%= link_to 'Profil', current_user, class: 'dropdown-item'%>
                  <div class="dropdown-divider"></div>
                  <%= link_to  destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                    <%= fa_icon "sign-out" %> Logout
                  <% end %>
                </div>
            </li>

        <% end %>
      </ul>
    </div>


    </div>
  </div>
</nav>

app/views/games/about.html.erb
<h1>Über</h1>

app/views/games/index.html.erb
<div class='jumbotron'>
<h1>Gamestats</h1>
<p>Eine kleine App zum festhalten von Kartenspielergebnissen mit schönen Grafiken zum Auswerten ... </p>
<%= link_to 'Login', new_user_session_path, class:'btn btn-outline-primary' %>
<%= link_to 'Registrieren', new_user_registration_path, class:'btn btn-outline-secondary' %>

  <% @allUsers.each do |u|%>
  <%= u.vorname %>
  <br/>
  <% end %>

</div>

app/views/games/myMatches.html.erb
<h1>Meine Spiele</h1>

<% @matches_days.each do |day| %>
  <div class="date">
    <%= day[0].strftime("%d. %b %Y") %>
  </div>

  <% @matches.each do |match| %>
  <% player1 = User.find(match.player1) %>
  <% player2 = User.find(match.player2) %>

    <% if player1 == current_user or player2 == current_user%>
      <% if match.created_at.strftime("%d. %b %Y") == day[0].strftime("%d. %b %Y") %>



    <div class='card'>
      <% if win_or_lose(match) == "Win" %>
        <div class='card-body won'>
      <% elsif win_or_lose(match) == "Lose" %>
        <div class='card-body lost'>
      <% else %>
        <div class='card-body'>
      <% end %>

      <h5>

        <%= link_to player1 do %>
          <div class="avatar left">
            <%= image_tag(player1.avatar.url(:thumb))%>
          </div>
        <% end %>
        <%= link_to player2 do %>
          <div class="avatar right">
            <%= image_tag(player2.avatar.url(:thumb))%>
          </div>
        <% end %>

        <div class='rivals'>
        <%= link_to "#{player1.vorname} vs. #{player2.vorname}", match, class:'card-title' %>
        </div>
      </h5>

      <h6 class='card-subtitle text-muted'>
          <%= match.game %>
      </h6>

      <div class='result'>
        <%= match.scoreplayer1 %>
        :
        <%= match.scoreplayer2 %>
      </div>

      <br>

      <% if match.user == current_user %>
      <div class='edit_match'>
        <%= link_to 'Löschen', match, method: :delete, data: { confirm: 'Sicher?' }, class:'card-link' %>
      </div>
      <% end %>

      <div class='timestamp'>
        <%= date_format(match.created_at) %>
      </div>
    </div>
    </div>
  <% end %>
<% end %>
<% end %>
<% end %>
<br><br>

app/views/games/ranking.html.erb
<h1>Ranking</h1>

<br>

  <% x= 1 %>
  <% @allUsers.each do |user| %>
  <div class="row ranking_row">
    <div class="col">
      <div class='ranking_number'><%= x %>

      <%= link_to user do %>
        <%= image_tag(user.avatar.url(:thumb), class:'nav_avatar')%>
        <%= user.vorname %>
      <% end %>
      </div>
    </div>

    <div class="col">
      <span class='ranking_main'><%= user.score %></span><br>
      <p class='ranking_sub'>SCORE</p>
    </div>

    <div class="col">
      <% all_matches = user.lost_matches + user.won_matches %>
      <span class='ranking_main'><%= all_matches %></span><br>
        <p class='ranking_sub'>SPIELE</p>
    </div>

    <div class="col">
        <%if all_matches > 0 %>
          <span class='ranking_main'><%= ((user.won_matches*1.0/all_matches)*100).round%>
          % </span><br>
            <p class='ranking_sub'>QUOTE</p>
        <% else %>
        <span class='ranking_main'>  0</span>
        <p class='ranking_sub'>QUOTE</p>
        <% end %>
    </div>
    </div>

  <% x+=1 %>
  <% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamestats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js", 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'games/header' %>

    <div class='container'>
      <p class='notice'><%= notice %></p>
      <p class='alert'><%= alert %></p>
      <%= yield %>
    </div>

  </body>
</html>

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='px-4 py-3' >

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <label class="input-group-text" for="inputGroupSelect01">Spiel</label>
    </div>
    <%= form.select :game, options_for_select([['Romme'], ['Mau Mau']]), {},  {class: 'custom-select'}%>
  </div>


  <div class="form-group">
    <%= form.hidden_field :player1, :value => @user.id %>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <label class="input-group-text" for="inputGroupSelect01">Gegner</label>
    </div>
    <%= form.select :player2, options_for_select(@allUsers.collect {|p| [p.vorname, p.id]}), {},  {class: 'custom-select'} %>
  </div>
<br><br>

  <div class="flex_container">
    <div class="match_score_card">

        <div class="input-group-prepend">
          <span class="match_score_head">Du</span>
        </div>
          <%= form.number_field :scoreplayer1, class:'match_score', :value => '0' %>
      </div>
      <div class="match_score_card">
          <div class="input-group-prepend">
            <span class="match_score_head">Gegner</span>
          </div>
          <%= form.number_field :scoreplayer2, class:'match_score', :value => '0' %>
    </div>
  </div>

<br>
<br>
  <div class="actions">
    <%= form.submit class:'btn btn-primary'%>
  </div>
  </div>
<br>
<% end %>

app/views/matches/edit.html.erb
<h1>Spiel editieren</h1>
<br>
<%= render 'form', match: @match %>

app/views/matches/index.html.erb
<h1>Spiele</h1>

<% @matches_days.each do |day| %>
  <div class="date">
    <%= day[0].strftime("%d. %b %Y") %>
  </div>

    <% @matches.each do |match| %>
    <% if match.created_at.strftime("%d. %b %Y") == day[0].strftime("%d. %b %Y") %>
      <div class='card'>
        <div class='card-body'>
          <% player1 = User.find(match.player1) %>
          <% player2 = User.find(match.player2) %>
        <h5>

          <%= link_to player1 do %>
            <div class="avatar left">
              <%= image_tag(player1.avatar.url(:thumb))%>
            </div>
          <% end %>
          <%= link_to player2 do %>
            <div class="avatar right">
              <%= image_tag(player2.avatar.url(:thumb))%>
            </div>
          <% end %>
          <div class='rivals'>
          <%= link_to "#{player1.vorname} vs. #{player2.vorname}", match, class:'card-title' %>
          </div>
        </h5>
        <h6 class='card-subtitle text-muted'>
            <%= match.game %>
        </h6>
        <div class='result'>
          <%= match.scoreplayer1 %>
          :
          <%= match.scoreplayer2 %>
        </div>
        <br>
        <div class='timestamp'>
          <%= date_format(match.created_at) %>
        </div>

        </div>
      </div>

      <% end %>
    <% end %>

<% end %>

<br>
<br>

app/views/matches/new.html.erb
<h1>Neues Spiel</h1>
<br>
<%= render 'form', match: @match %>

app/views/matches/show.html.erb
<% player1 = User.find(@match.player1) %>
<% player2 = User.find(@match.player2) %>
<div class='px-4 py-3' >

<%= date_format(@match.created_at) %>

  <div class='card-body'>

  <h5>

    <%= link_to player1 do %>
      <div class="avatar_medium left">
        <%= image_tag(player1.avatar.url(:medium))%>
      </div>
    <% end %>
    <%= link_to player2 do %>
      <div class="avatar_medium right">
        <%= image_tag(player2.avatar.url(:medium))%>
      </div>
    <% end %>
    <div class='rivals' style='font-size: 1.5em;'>
      <%= player1.vorname%> vs.
      <%= player2.vorname%>

    </div>
  </h5>
  <h6 class='card-subtitle text-muted'>
      <%= @match.game %>
  </h6>
  <div class='result' style='font-size: 3em;'>
    <%= @match.scoreplayer1 %>
    :
    <%= @match.scoreplayer2 %>
  </div>
  <br>


  </div>
</div>
<br><br><br>
<%= link_to 'Alle Spiele', matches_path %>

app/views/users/show.html.erb
<h1><%= @user.vorname %></h1>
<div class='flexbox_container'>
  <div class='avatar_box'>
    <%= image_tag (@user.avatar.url(:medium)), class:'avatar_big' %>
  </div>

  <div class='stats_box'>
    <h3>Info</h3>
    <b>Name:</b>
    <%= @user.vorname + ' '+ @user.nachname %>
    <br>
    <b>Score:</b>
      <%= @user.score %>
    <br/>

    <b>Spiele:</b>
      <%= all_matches = @user.lost_matches + @user.won_matches %>
    <br />

    <b>Quote:</b>
    <% if all_matches != 0 %>
      <%= ((@user.won_matches*1.0/all_matches)*100).round %> %
      <% end %>
    <br />

    <b>Verlorene Spiele</b>
      <%= @user.lost_matches %>
    <br />

    <b>Gewonnene Spiele</b>
      <%= @user.won_matches %>
    <br />
  </div>


<div class='opponents'>
    <% opponent = [] %>
    <% @my_matches.each do |match| %>

        <% player1 = User.find(match.player1) %>
        <% player2 = User.find(match.player2) %>

        <%if (@user != player1) && (@user == player2) %>
          <% opponent.push(player1.id) %>
        <%end %>

        <%if (@user != player2) && (@user == player1) %>
          <% opponent.push(player2.id) %>
        <%end %>
    <% end %>

    <% opponent_matches = opponent.inject(Hash.new(0)) { |total, e| total[e] += 1 ;total} %>
    <% opponent_matches = opponent_matches.sort_by { |id, matches| matches }.reverse %>
    <% opponent_matches.first(1).each do |match| %>
      <% opponent = User.find(match[0]) %>
      <h4>Lieblingsgegner: <%= opponent.vorname %></h4>
      <br>
      <%= link_to opponent do %>
      <%= image_tag (opponent.avatar.url(:thumb)), class:'avatar' %>
      <% end %>
      <br>
      Duelle:
      <%= match[1] %>
      <br>
      <% opponents_duelle = Match.where('player1 = ? OR player2 = ?', opponent.id, opponent.id) %>
      <% duelle = opponents_duelle.where('player1 = ? OR player2 = ?', @user.id, @user.id) %>
      <% gewonnene_duelle = 0 %>
      <% verlorene_duelle = 0 %>
      <% duelle.each do |duell| %>

        <% player1 = User.find(duell.player1) %>
        <% player2 = User.find(duell.player2) %>

        <% if player1 == opponent%>

          <% if duell.scoreplayer1 < duell.scoreplayer2 %>
          <% verlorene_duelle = verlorene_duelle +1 %>
          <% else %>
          <% gewonnene_duelle = gewonnene_duelle +1 %>

          <% end %>

        <% end %>

        <% if player2 == opponent %>

          <%if duell.scoreplayer1 > duell.scoreplayer2 %>
          <% verlorene_duelle = verlorene_duelle +1 %>
          <% else %>
          <% gewonnene_duelle = gewonnene_duelle +1 %>
          <% end %>

        <% end %>

        <% end %>
        Gegen <%= @user.vorname %> verloren:
        <%= verlorene_duelle %>
        <br>
        Gegen <%= @user.vorname %> gewonnen:
        <%= gewonnene_duelle %>
    <% end %>


</div>
</div>
<% i = 1 %>
<% score = 1000 %>
<% hash = {} %>


<% @my_matches.each do |match| %>

  <% player1 = User.find(match.player1) %>
  <% player2 = User.find(match.player2) %>
  <% i %>
  <% date_format(match.created_at) %>

  <% if player1 == @user %>
    <% player2.vorname %>
    <% if match.scoreplayer1 > match.scoreplayer2 %>
      <%# Verloren %>
      <% score = score + (match.scoreplayer2 - match.scoreplayer1) %>
      <% hash.store(i, score) %>
    <% else %>
      <%# Gewonnen %>
      <% score = score + (match.scoreplayer2 + match.scoreplayer1) %>
      <% hash.store(i, score) %>
    <% end %>
    <% i = i + 1 %>

  <% elsif player2 == @user %>
    <% player1.vorname %>
    <% if match.scoreplayer1 > match.scoreplayer2 %>
      <%# Gewonnen %>
      <% score = score + (match.scoreplayer1+ match.scoreplayer2) %>
      <% hash.store(i, score) %>

    <% else %>
      <%# Verloren %>
      <% score = score + (match.scoreplayer1- match.scoreplayer2) %>
      <% hash.store(i, score) %>

    <% end %>
    <% i = i + 1 %>

  <% end %>
<% end %>

<br>

<%= line_chart hash, {library: {hAxis: {title: "Spiele"}, vAxis: {title: "Score"}, pointSize: 0,}, colors:['red','#004411'], curveType: 'function', legend: 'none'}  %>